version: 2.1

# build job parameters as a template
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress dependencies
    - image: cypress/included:7.7.0
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - app

  testLogin:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running E2E tests with multiple reporters for Login
          command: npm run test-login
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  testSearch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running E2E tests with multiple reporters for Search
          command: npm run test-search
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  testApi:
    <<: *defaults
    parallelism: 1
    # parallelism: 2
    parameters:
      API_endpoint:
        type: string
        default: ""
    steps:
      # Comment out for tests splitting - need to test
      # - run:
      #     name: Split test
      #     command: |
      #       circleci tests glob **/integration/apitest/*.feature | circleci tests split --split-by=timings
      - attach_workspace:
          at: ~/
      - when:
          condition: 
            equal: [User, << parameters.API_endpoint >> ]
          steps:
            - run:
                name: Running API tests with multiple reporters for API User
                command: npm run test-api-user
      - when:
          condition: 
            equal: [Car, << parameters.API_endpoint >> ]
          steps:
            - run:
                name: Running API tests with multiple reporters for API Car
                command: npm run test-api-car
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  build-and-test:
    jobs:
      - build
      - testLogin:
          requires:
            - build
      - testSearch:
          requires:
            - build
      - testApi:
          name: Test API User
          API_endpoint: "User"
          requires:
            - build
      - testApi:
          name: Test API Car
          API_endpoint: "Car"
          requires:
            - build
            
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 16 20 * *"
          filters:
            branches:
              only: main
    jobs:
      - build
      - testLogin:
          requires:
            - build
      - testSearch:
          requires:
            - build
      - testApi:
          name: Test API User
          API_endpoint: "User"
          requires:
            - build
      - testApi:
          name: Test API Car
          API_endpoint: "Car"
          requires:
            - build
